# Generated by Django 5.2 on 2025-05-31 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pfa_projects', '0002_initial'),
        ('pfa_teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectchoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa_projects.project'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_team', to='pfa_projects.project'),
        ),
        migrations.AddField(
            model_name='team',
            name='subject_choices',
            field=models.ManyToManyField(related_name='interested_teams', through='pfa_teams.SubjectChoice', to='pfa_projects.project'),
        ),
        migrations.AddField(
            model_name='subjectchoice',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa_teams.team'),
        ),
        migrations.AddField(
            model_name='message',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pfa_teams.team'),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pfa_teams.team'),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subjectchoice',
            unique_together={('team', 'priority')},
        ),
        migrations.AlterUniqueTogether(
            name='teamrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
