# Generated by Django 5.2 on 2025-06-01 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa_projects', '0003_project_max_students'),
        ('pfa_teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to='pfa_projects.project'),
        ),
    ]
