# Generated by Django 5.2.3 on 2025-06-24 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa_teams', '0004_add_reports_and_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='pfa_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
