# Generated by Django 5.2 on 2025-05-31 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pfa_projects', '0001_initial'),
        ('pfa_teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='pfa_projects.project'),
        ),
        migrations.AddField(
            model_name='projectstatistics',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='pfa_projects.project'),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pfa_projects.project'),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfa_teams.team'),
        ),
        migrations.AddField(
            model_name='report',
            name='deadline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfa_projects.deadline'),
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pfa_projects.project'),
        ),
        migrations.AddField(
            model_name='report',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='pfa_teams.team'),
        ),
    ]
