# Generated by Django 5.2 on 2025-06-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa_projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_students',
            field=models.IntegerField(default=2),
        ),
    ]
